### ISSUE TITLE
No available for any of my Devices

### ISSUE THREAD

**Issue by Yelrado** [Microsoft/ProjectOxford-Apps-MimickerAlarm#1]
I tried to install this app from the Play Store and even though I have the OnePlus One updated, it says it's not available for my phone.

Location: México.

**Comment by lightfrenzy** [comment]
Hi, yelrado!

Right now, we have limited availability and are exploring options for expanding. I'll let you know when we have an update on this.

Thanks for reaching out!
-Allison

**Comment by lightfrenzy** [comment]
Good news

Mimicker Alarm is now available in Brazil, Colombia, Mexico, Russia, UAE (support for English only). You can download it on the Google Play Store:
    https://play.google.com/store/apps/details?id=com.microsoft.mimickeralarm

Thanks again for contacting us!
-Allison
