### ISSUE TITLE
This app is incompatible with your device.

### ISSUE THREAD

**Issue by Maslor** [Microsoft/ProjectOxford-Apps-MimickerAlarm#2]
Are you currently still testing the app for a broader range of devices? By the way, what is the hardware/software feature that devices must have in order to be compatible with Mimicker alarm?

**Comment by CezaryDanielNowak** [comment]
Xperia Z1 Compact, impossible to install from Play Store as well

**Comment by ryush00** [comment]
LG G3, impossible to install from Play Store.

**Comment by sakrifor** [comment]
Moto G 2nd Gen Android 5.0.2 can't install from Playstore

**Comment by flanaras** [comment]
Can't install on Nexus 5 with android version 6.0.1

**Comment by delfu** [comment]
Hi! 
If you are trying to download from the Play Store and it says it not compatible, make sure that : 
1. your device is at least on android 4.1
2. your device is at least mdpi (~160 dpi) http://developer.android.com/guide/practices/screens_support.html
   devices smaller/less pixel density than that is not yet supported 
3. Your play store is one of the countries the app is currently released in. 
   This is the most likely reason why you can't download (yet). Play store sometimes has a weird quirk of saying it's not compatible with your device when it means it's not available in your country.

**Comment by Maslor** [comment]
I guess you're right @dlfu , it's probably not available in Portugal yet. Is there a list of countries where the app is already available?

**Comment by lightfrenzy** [comment]
Hi, everyone,

Great news, the app is now available worldwide so all of you should be able to download. If you're still having problems, and you have a device running Android 4.1+, please open a new issue so we can investigate.

Download the app now at https://play.google.com/store/apps/details?id=com.microsoft.mimickeralarm.

Thanks!
